name: CI
on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify current directory
        run: echo $PWD && ls -la
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHP 7.4 DEV - Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chrisb9/pimcore-dev
          tags: 7.4-dev
          build_args: FROM=pluswerk/php-dev:nginx-7.4
          path: .
      - name: PHP 7.4 - Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chrisb9/pimcore-dev
          tags: 7.4
          build_args: FROM=webdevops/php-nginx:7.4
          path: .
