name: CI
on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Verify current directory
        run: echo $PWD && ls -la
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: PHP ${{ matrix.php }} DEV Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chrisb9/pimcore-dev
          tags: ${{ matrix.php }}-dev
          build_args: FROM=pluswerk/php-dev:nginx-${{ matrix.php }}
          path: .
      - name: PHP ${{ matrix.php }} - Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chrisb9/pimcore-dev
          tags: ${{ matrix.php }}
          build_args: FROM=webdevops/php-nginx:${{ matrix.php }}
          path: .
